spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server: 
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/tinywet/sp-config
#          searchPaths: config
#          username: tinywet
#          password: woshi479987406!
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
